# Generated by Django 4.2.28 on 2026-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('pm', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('complete', 'Complete')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['name'],
            },
        ),
    ]
