# Generated by Django 4.2.28 on 2026-02-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_number_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
