# Generated by Django 4.2.28 on 2026-02-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_project_address'),
        ('core', '0003_add_whiteboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeatherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geocode_source', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_location', to='projects.project')),
            ],
            options={
                'db_table': 'core_projectweatherlocation',
            },
        ),
        migrations.CreateModel(
            name='ProjectWeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_json', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='projects.project')),
            ],
            options={
                'db_table': 'core_projectweathercache',
            },
        ),
    ]
