# Generated by Django 4.2.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_project_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_add_weather_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='link_to_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_cards', to='core.board'),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_cards', to='projects.project'),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='whiteboardcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
