# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whiteboard_board_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('TEXT', 'Text'), ('BOX', 'Box')], default='NOTE', max_length=10)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('w', models.FloatField(default=120)),
                ('h', models.FloatField(default=80)),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.board')),
            ],
            options={
                'db_table': 'core_whiteboarditem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('arrow', 'Arrow'), ('plain', 'Plain')], default='arrow', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.board')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='core.whiteboarditem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='core.whiteboarditem')),
            ],
            options={
                'db_table': 'core_whiteboardlink',
            },
        ),
    ]
