# Generated by Django 4.2.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_whiteboarditem_whiteboardlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboarditem',
            name='shape',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
