# Generated by Django 4.2.28 on 2026-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='task_type_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work_type',
            field=models.CharField(choices=[('baseline_schedule_review', 'Baseline schedule review'), ('schedule_update', 'Schedule update'), ('schedule_update_review', 'Schedule update review'), ('claim_analysis', 'Claim analysis'), ('other', 'Other')], default='schedule_update', max_length=50),
        ),
    ]
