# Generated by Django 4.2.28 on 2026-02-15 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_backfill_work_type_to_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
