# Generated by Django 4.2.28 on 2026-02-15 23:37

from django.db import migrations, models


def map_old_priorities(apps, schema_editor):
    """
    Priority mapping:
    - P0/P1 -> high
    - P2    -> medium
    - P3    -> low
    """
    WorkItem = apps.get_model('work', 'WorkItem')
    WorkItem.objects.filter(priority__in=['P0', 'P1']).update(priority='high')
    WorkItem.objects.filter(priority='P2').update(priority='medium')
    WorkItem.objects.filter(priority='P3').update(priority='low')


def reverse_map_priorities(apps, schema_editor):
    WorkItem = apps.get_model('work', 'WorkItem')
    WorkItem.objects.filter(priority='high').update(priority='P1')
    WorkItem.objects.filter(priority='medium').update(priority='P2')
    WorkItem.objects.filter(priority='low').update(priority='P3')


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_soft_delete_and_updated_by'),
    ]

    operations = [
        migrations.RunPython(map_old_priorities, reverse_map_priorities),
        migrations.AlterField(
            model_name='workitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
