# Generated by Django 4.2.28 on 2026-02-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_priority_to_low_medium_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
