# Generated by Django 4.2.28 on 2026-02-21 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_add_project_address'),
        ('work', '0006_add_meeting_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='work_type',
            field=models.CharField(choices=[('baseline_schedule_review', 'Baseline schedule review'), ('schedule_update', 'Schedule update'), ('schedule_update_review', 'Schedule update review'), ('claim_analysis', 'Claim analysis'), ('update_request', 'Update request'), ('other', 'Other')], default='schedule_update', max_length=50),
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('target_users', models.CharField(blank=True, help_text='Who needs to reply (names or roles)', max_length=500)),
                ('message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('reply_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reply_outcome', models.CharField(blank=True, choices=[('all_answered', 'All answered'), ('needs_follow_up', 'Needs follow-up')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('follow_up_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_update_request', to='work.workitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='projects.project')),
                ('source_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_update_requests', to='work.workitem')),
            ],
            options={
                'db_table': 'work_updaterequest',
                'ordering': ['-sent_at'],
            },
        ),
    ]
