# Generated by Django 4.2.28 on 2026-02-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_project_address'),
        ('work', '0007_alter_workitem_work_type_updaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='projects.project'),
        ),
    ]
