# Generated by Django 4.2.28 on 2026-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='work_code',
            field=models.CharField(blank=True, choices=[('schedule_update', 'Schedule update'), ('baseline_update', 'Baseline update'), ('schedule_analysis', 'Schedule analysis')], max_length=50),
        ),
    ]
