# Generated by Django 4.2.28 on 2026-02-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_project_address'),
        ('time_tracking', '0002_add_work_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project'),
        ),
    ]
