# Generated by Django 4.2.28 on 2026-03-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_optional_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
    ]
